basis: aug-cc-pVQZ
auxbasis: aug-cc-pV5Z-RIFIT
xc: PBE0
excitations: 
    Cyclopropene: {"B1": [-1, 1]}
    Diazomethane: {"B1": [0, 2], "A1": [0, 3]}
    Ethylene: {"B3u": [0, 2], "B1g": [0, 3]}
    Formaldehyde: {"A1_pi": [-1, 1], "B2_3s": [0, 2], "B2_3p": [0, 4], "A1_3p": [0, 3]}
    Formamide: {"A'": [-1, 2]}
    Hydrogen sulfide: {"B1": [0, 1]}
    Ketene: {"B1": [0, 2], "A2_3p": [0, 4]}
    Thioformaldehyde: {"B2": [0, 2], "A1": [-1, 1]}
    Water: {"A2": [0, 2], "A1": [-1, 1]}
grid_level: 3
frac_occ: False
systems: ["Cyclopropene", "Diazomethane", "Ethylene", "Formaldehyde", "Formamide", "Hydrogen sulfide", "Ketene", "Thioformaldehyde", "Water"]
