basis: aug-cc-pVQZ
auxbasis: aug-cc-pV5Z-RIFIT
xc: SVWN
excitations:
    Aminobenzonitrile: {"A1":[0, 1]}
    Aniline: {"A1":[0, 2]}
    Azulene: {"A1":[0, 2], "B2":[-1, 2]}
    Benzonitrile: {"A2":[-2, 1]}
    Benzothiadiazole: {"B2":[0, 1]}
    Dimethylaminobenzonitrile: {"A1":[0, 1]}
    Dimethylaniline: {"B2": [0, 1], "A1": [0, 3]}
    Hydrogen chloride: {"Pi": [0, 1]}
    Nitroaniline: {"A1": [0, 1]}
    Nitrobenzene: {"A1":[-2, 1]}
    Nitrodimethylaniline: {"A1": [0, 1]}
    Nitropyridine N-Oxide: {"A1": [0, 1]}
    N-Phenylpyrrole: {"B2": [0, 1], "A1": [0, 2]}
    Phthalazine: {"A2": [0, 1], "B1":[0, 2]}
    Quinoxaline: {"B2": [-1, 1], "A1":[-1,2], "B1":[0,3]}
    Twisted DMABN: {"A2":[0, 1], "B1":[0, 2]}
    Twisted PP: {"B2": [0, 1], "A1": [0, 2], "A2":[-1, 1], "B1":[-1, 2]}
grid_level: 3
frac_occ: True
systems: null
