basis: aug-cc-pVQZ
oep_basis: aug-cc-pVDZ-RIFIT
dfit_basis: aug-cc-pV5Z-RIFIT
xc: SVWN
excitation: [0, 1]
exceptions: {"Hydrogen sulfide": [0, 2]}
grid_level: 3
systems: null
space_sym: True
thr_fai_oep: 0.017
conv_thr: 0.00000001
swap: True
